[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/all-projets"
  to = "/.netlify/functions/all-projects"
  status = 200
  force = true

[[redirects]]
  from = "/api/project/:id"
  to = "/.netlify/functions/project/:id"
  status = 200

[context.dev.environment]
  NODE_ENV= "devlopment"
  LOCAL_HOST="http://localhost:8888"  