[build]
  publish = "dist"
  functions = "netlify/functions"
   
[[redirects]]
  from= "/api/all-projects"
  to = "/.netlify/functions/all-projects"
  status= 200

[[redirects]]
  from= "/api/project id:id"
  to = "/.netlify/functions/project/:id"
  status= 200