[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/all-projets"
  to = "/.netlify/functions/all-projects"
  status = 200
  force = true

[[redirects]]
  from = "/api/project"
  to = "/.netlify/functions/project"
  status = 200
  force = true